/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GYM;

import java.awt.Component;
import static java.awt.PageAttributes.MediaType.C;
import java.io.*;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
//import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        findBtn = new javax.swing.JButton();
        payBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        attendBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        memberPane = new javax.swing.JScrollPane();
        mbrTable = new javax.swing.JTable();
        attendPane = new javax.swing.JScrollPane();
        attendTable = new javax.swing.JTable();
        payPane = new javax.swing.JScrollPane();
        payTable = new javax.swing.JTable();
        addForm = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtdoj = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        findForm = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        attendForm = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtinhour = new javax.swing.JTextField();
        txtaname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnmark = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtouthour = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        payForm = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        txtpmobile = new javax.swing.JTextField();
        txtdop = new javax.swing.JTextField();
        btnpay = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(40, 5));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 153, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-add-user-male-96.png"))); // NOI18N
        addBtn.setText("Add Member");
        addBtn.setBorderPainted(false);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, -1));

        findBtn.setBackground(new java.awt.Color(255, 255, 255));
        findBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        findBtn.setForeground(new java.awt.Color(0, 153, 255));
        findBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-find-user-male-96.png"))); // NOI18N
        findBtn.setText("Find Member");
        findBtn.setBorderPainted(false);
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });
        getContentPane().add(findBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, -1));

        payBtn.setBackground(new java.awt.Color(255, 255, 255));
        payBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        payBtn.setForeground(new java.awt.Color(0, 153, 255));
        payBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-cash-in-hand-96.png"))); // NOI18N
        payBtn.setText("Payments");
        payBtn.setBorderPainted(false);
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });
        getContentPane().add(payBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 290, -1));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-close-window-24 (1).png"))); // NOI18N
        exitBtn.setBorder(null);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 20, 20));

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 153, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-del-user-male-96.png"))); // NOI18N
        deleteBtn.setText("Delete Member");
        deleteBtn.setBorderPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, -1));

        attendBtn.setBackground(new java.awt.Color(255, 255, 255));
        attendBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        attendBtn.setForeground(new java.awt.Color(0, 153, 255));
        attendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-attendance-96.png"))); // NOI18N
        attendBtn.setText("Attendance");
        attendBtn.setBorderPainted(false);
        attendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(attendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 290, -1));

        listBtn.setBackground(new java.awt.Color(255, 255, 255));
        listBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        listBtn.setForeground(new java.awt.Color(0, 153, 255));
        listBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-list-96.png"))); // NOI18N
        listBtn.setText("ListofMembers");
        listBtn.setBorderPainted(false);
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });
        getContentPane().add(listBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, -1));

        mbrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Address", "Mobile", "Date Of Join"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mbrTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mbrTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        memberPane.setViewportView(mbrTable);

        getContentPane().add(memberPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 470));

        attendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "member name", "weigt", "entry hour", "exit hour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attendPane.setViewportView(attendTable);

        getContentPane().add(attendPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 470));

        payTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "mobile", "data of pay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        payPane.setViewportView(payTable);

        getContentPane().add(payPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 470));

        addForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-name-32.png"))); // NOI18N
        jLabel5.setText("name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-age-32.png"))); // NOI18N
        jLabel7.setText("Age");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-user-location-32.png"))); // NOI18N
        jLabel9.setText("Address");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-phone-32.png"))); // NOI18N
        jLabel10.setText("moblie");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-date-to-32.png"))); // NOI18N
        jLabel11.setText("Date of join");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });

        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });

        txtdoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdojActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(255, 204, 204));
        btnadd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnadd.setForeground(new java.awt.Color(0, 153, 255));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-add-user-male-32.png"))); // NOI18N
        btnadd.setText("Add");
        btnadd.setBorder(null);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE))
                            .addComponent(txtdoj)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtmobile, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaddress))))
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtdoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnadd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addForm.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 400));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-add-user-male-64.png"))); // NOI18N
        jLabel1.setText(" Add Member Form");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        addForm.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(addForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 440, 470));

        findForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel7.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 370, 40));

        findForm.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 380));

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-find-user-male-64.png"))); // NOI18N
        jLabel2.setText("Find Member Form");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        findForm.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        getContentPane().add(findForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 440, 470));

        attendForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-name-32.png"))); // NOI18N
        jLabel8.setText("Member name");
        attendForm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-weight-kg-32.png"))); // NOI18N
        jLabel12.setText("Wight");
        attendForm.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-login-32.png"))); // NOI18N
        jLabel13.setText("Entery hour");
        attendForm.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, -1));
        attendForm.add(txtinhour, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 220, -1));
        attendForm.add(txtaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 220, -1));

        jLabel14.setText("KG");
        attendForm.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 20, 20));

        btnmark.setBackground(new java.awt.Color(0, 153, 255));
        btnmark.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btnmark.setForeground(new java.awt.Color(0, 153, 255));
        btnmark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-checked-32.png"))); // NOI18N
        btnmark.setText("Mark");
        btnmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarkActionPerformed(evt);
            }
        });
        attendForm.add(btnmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 140, 40));

        jLabel15.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-logout-rounded-left-32.png"))); // NOI18N
        jLabel15.setText("Exit hour");
        attendForm.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, -1));

        txtouthour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtouthourActionPerformed(evt);
            }
        });
        attendForm.add(txtouthour, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 220, -1));
        attendForm.add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, -1));

        jPanel8.setBackground(new java.awt.Color(0, 153, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-attendance-9w6.png"))); // NOI18N
        jLabel6.setText("Attendance Member Form");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        attendForm.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        getContentPane().add(attendForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 440, 470));

        payForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-name-32.png"))); // NOI18N
        jLabel16.setText("name");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-phone-32.png"))); // NOI18N
        jLabel19.setText("moblie");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/icons8-pay-date-32.png"))); // NOI18N
        jLabel20.setText("Date of pay");

        txtpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpnameActionPerformed(evt);
            }
        });

        txtpmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpmobileActionPerformed(evt);
            }
        });

        txtdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdopActionPerformed(evt);
            }
        });

        btnpay.setBackground(new java.awt.Color(255, 204, 204));
        btnpay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnpay.setForeground(new java.awt.Color(0, 153, 255));
        btnpay.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\icons8-cash-in-hand-32.png")); // NOI18N
        btnpay.setText("Pay");
        btnpay.setBorder(null);
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtpmobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtpname, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtdop, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnpay, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtpmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtdop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnpay)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        payForm.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 440, 390));

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\icons8-cash-in-hand-96 (w).png")); // NOI18N
        jLabel4.setText("Pay Member Form");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        payForm.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 90));

        getContentPane().add(payForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 440, 470));

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GYM/young-fitness-man-studio.png"))); // NOI18N
        background.setLabelFor(payBtn);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // TODO add your handling code here:
         memberPane.setVisible(false);
         attendPane.setVisible(false);
         payPane.setVisible(true);
         
         mbrTable.setVisible(false);
         attendTable.setVisible(false);
         payTable.setVisible(true);
        
          addForm.setVisible(false);
         findForm.setVisible(false);
        attendForm.setVisible(false);
         payForm.setVisible(true);
       
      
        
    }//GEN-LAST:event_payBtnActionPerformed

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:
       
        attendForm.setVisible(false);
        payForm.setVisible(false);
        addForm.setVisible(false);
        search.setVisible(true);
        findForm.setVisible(true);
        memberPane.setVisible(true);
        mbrTable.setVisible(true);
       // findForm.setVisible(true);
         
    }//GEN-LAST:event_findBtnActionPerformed
boolean readed = false;
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        BufferedReader br=null;
            findForm.setVisible(false);
            attendForm.setVisible(false);
            payForm.setVisible(false);
            addForm.setVisible(true);
            memberPane.setVisible(true);
            mbrTable.setVisible(true);
             
             if(!readed){
            File file=new File("C:\\Users\\HP\\Documents\\NetBeansProjects\\GymManagementSystem\\src\\main\\java\\GYM\\member.txt");
            DefaultTableModel tm=(DefaultTableModel) mbrTable.getModel();
        try {
            // TODO add your handling code here:
            br = new BufferedReader(new FileReader(file));
                Object [] tableLine = br.lines().toArray();
                
            for (Object tableLine1 : tableLine) {
                String line = tableLine1.toString().trim();
                String [] dataRow=line.split(";");
                tm.addRow(dataRow); 
                br.close();
                readed = true;
            }
                
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }}
             else{;}
        
        

    }//GEN-LAST:event_addBtnActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked

    }//GEN-LAST:event_addBtnMouseClicked

    private void mbrTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mbrTableAncestorAdded

    }//GEN-LAST:event_mbrTableAncestorAdded

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void txtdojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdojActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
      
        if (txtname.getText().equals("") || txtage.getText().equals("") || txtaddress.getText().equals("")
                || txtmobile.getText().equals("") || txtdoj.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please fill the Table content ");
        } else {
            String data[] = {txtname.getText(), txtage.getText(), txtaddress.getText(),
                txtmobile.getText(), txtdoj.getText()};
            
            DefaultTableModel tm = (DefaultTableModel) mbrTable.getModel();
            tm.addRow(data);
            try {
            File file=new File("C:\\Users\\HP\\Documents\\NetBeansProjects\\GymManagementSystem\\src\\main\\java\\GYM\\member.txt");
                if(!file.exists()) {
                    file.createNewFile();
                }
                FileWriter fw=new FileWriter(file.getAbsoluteFile());
                BufferedWriter bw=new BufferedWriter(fw);
                
                for(int i=0;i<mbrTable.getRowCount();i++){
                    for(int j=0;j<mbrTable.getColumnCount();j++){
                        bw.write((String) mbrTable.getModel().getValueAt(i, j)+" ;");
                    }
                   // bw.write("\n      \n");
                   bw.write("\n");
                    
                }
                bw.close();
                fw.close();
                
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(this, "member added");
            //clear text
            txtname.setText("");
            txtage.setText("");
            txtaddress.setText("");
            txtmobile.setText("");
            txtdoj.setText("");
       addForm.setVisible(false);

        }
        
       // jPanel1.setVisible(false);
        // mbrTable.setVisible(false);
      
     /*INSERT INTO `gms`.`member`
(`member_name`,
`member_age`,
`member_address`,
`member_mobile`,
`memberdoj`)
VALUES
(<{member_name: }>,
<{member_age: }>,
<{member_address: }>,
<{member_mobile: }>,
<{memberdoj: }>);
     if (txtname.getText().equals("") || txtage.getText().equals("") || txtaddress.getText().equals("")
                || txtmobile.getText().equals("") || txtdoj.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please fill the Table content ");
        } else {
     try {  
        Class.forName("com.mysql.cj.jdbc.Driver");  
        
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gms","root","1234");  
        Statement statement = con.createStatement();  
        statement.executeUpdate("INSERT INTO member(name,age,address,mobile,date_of_join) VALUES('"+ txtname.getText() + "','" + txtage.getText() + "','" + txtaddress.getText() +"','"+ txtmobile.getText() +"','" + txtdoj.getText() + "')");  
        JOptionPane.showMessageDialog(null, "Member Added");  
                
        statement.close();  
        con.close();  
        Referesh(); 
         addForm.setVisible(false);
    } catch (SQLException | ClassNotFoundException e) {  
        JOptionPane.showMessageDialog(null, e);  
    }  
     }*/

     
    }//GEN-LAST:event_btnaddActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        Component yes = null;
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(yes, "do yo want ot exit");
        this.setVisible(false);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
               //JOptionPane.showMessageDialog(this, "please select member form table");
             // memberPane.setVisible(true);
             // mbrTable.setVisible(true);
            
        DefaultTableModel tm = (DefaultTableModel) mbrTable.getModel();

        if (mbrTable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "table is empety");
        } else {
            if (mbrTable.getSelectedRowCount() == 1) {
                tm.removeRow(mbrTable.getSelectedRow());
               // int x=mbrTable.getSelectedRow();
              //theQuery("delete from member where id="+x);
            } else {
                JOptionPane.showMessageDialog(this, "please select single row");
            }
              
        }
        
        
            
            
          
       
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void attendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendBtnActionPerformed
        // TODO add your handling code here: 
        addForm.setVisible(false);
        payForm.setVisible(false);
        findForm.setVisible(false);
        attendForm.setVisible(true);
        memberPane.setVisible(false);
        payPane.setVisible(false);
        attendPane.setVisible(true);
         attendTable.setVisible(true);
    }//GEN-LAST:event_attendBtnActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
        payPane.setVisible(false);
        memberPane.setVisible(true);
       
          mbrTable.setVisible(true);
          
         
//           Connection conn=null;
//         
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//             conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/gms","root","1234");
//            Statement stmt=conn.createStatement();
//            String query ="select * from member";
//            ResultSet rs=stmt.executeQuery(query);
//            //while(rs.next()){
//              /*
//                String id=String.valueOf(rs.getInt(1));
//                String name =rs.getString(2);
//                String age=rs.getString(3);
//                String address=rs.getString(4);
//                String mobile=rs.getString(5);
//                String doj=rs.getString(6);
//                String data []={name,age,address,mobile,doj};*/
//              
//               mbrTable.setModel(DbUtils.resultSetToTableModel(rs));
//               
//           //  }
//             
//        } catch (ClassNotFoundException | SQLException ex) {
//            
//        }
    }//GEN-LAST:event_listBtnActionPerformed

    private void btnmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarkActionPerformed
            if (txtaname.getText().equals("") || txtweight.getText().equals("") || txtinhour.getText().equals("")
                || txtouthour.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please fill the content ");
        } else {
            String data[] = {txtaname.getText(), txtweight.getText(), txtinhour.getText(),
                txtouthour.getText()};
            DefaultTableModel tm = (DefaultTableModel) attendTable.getModel();
            tm.addRow(data);
            JOptionPane.showMessageDialog(this, "Member Marked");
            //clear text
            txtaname.setText("");
            txtweight.setText("");
            txtinhour.setText("");
            txtouthour.setText("");
           

        }
        
       attendForm.setVisible(false);
        attendPane.setVisible(false);
       attendTable.setVisible(false);
        
    }//GEN-LAST:event_btnmarkActionPerformed

    private void txtouthourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtouthourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtouthourActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        // TODO add your handling code here:
           if (txtpname.getText().equals("") || txtpmobile.getText().equals("") || txtdop.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please fill the content ");
        } else {
            String data[] = {txtpname.getText(), txtpmobile.getText(), txtdop.getText()};
            DefaultTableModel tm = (DefaultTableModel) payTable.getModel();
            tm.addRow(data);
            JOptionPane.showMessageDialog(this, "done");
            //clear text
            txtpname.setText("");
            txtpmobile.setText("");
            txtdop.setText("");
           
           

        }
        
       payForm.setVisible(false);
       // payPane.setVisible(false);
      // payTable.setVisible(false);
        
  
    }//GEN-LAST:event_btnpayActionPerformed

    private void txtdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdopActionPerformed

    private void txtpmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpmobileActionPerformed

    private void txtpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpnameActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
         DefaultTableModel tm = (DefaultTableModel) mbrTable.getModel();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<>(tm); 
        mbrTable.setRowSorter(tr);
        String query=search.getText();
        tr.setRowFilter(RowFilter.regexFilter(query));
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main f1 = new Main();
             f1.addForm.setVisible(false);
             f1.findForm.setVisible(false);
             f1.payForm.setVisible(false);
             f1.attendForm.setVisible(false);
                //f1.mbrTable.setVisible(false);
                
             f1.memberPane.setVisible(false);
             f1.payPane.setVisible(false);
             f1.attendPane.setVisible(false);
             f1.search.setVisible(false);
                //f1.payTable.setVisible(false);
             
       
        
      
       
      
      
         
                //f1.attendTable.setVisible(false);
                f1.setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addForm;
    private javax.swing.JButton attendBtn;
    private javax.swing.JPanel attendForm;
    private javax.swing.JScrollPane attendPane;
    private javax.swing.JTable attendTable;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnmark;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton findBtn;
    private javax.swing.JPanel findForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton listBtn;
    private javax.swing.JTable mbrTable;
    private javax.swing.JScrollPane memberPane;
    private javax.swing.JButton payBtn;
    private javax.swing.JPanel payForm;
    private javax.swing.JScrollPane payPane;
    private javax.swing.JTable payTable;
    private javax.swing.JTextField search;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtaname;
    private javax.swing.JTextField txtdoj;
    private javax.swing.JTextField txtdop;
    private javax.swing.JTextField txtinhour;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtouthour;
    private javax.swing.JTextField txtpmobile;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables

    private void DBconnection() {
     
       
    }

    private void Referesh() {
         txtname.setText("");  
         txtage.setText("");  
         txtaddress.setText("");  
         txtmobile.setText("");  
         txtdoj.setText("");  
         
      //To change body of generated methods, choose Tools | Templates.
    }

    private void theQuery(String query) {
        //To change body of generated methods, choose Tools | Templates.
        try {  
        Class.forName("com.mysql.cj.jdbc.Driver");  
        // establish connection  
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gms","root","1234");  
        Statement statement = con.createStatement();  
        statement.executeUpdate(query);  
        JOptionPane.showMessageDialog(null, "The Query Executed");  
        statement.close();  
        con.close();  
      
    } catch (SQLException | ClassNotFoundException e) {  
        JOptionPane.showMessageDialog(null, e);  
    }
    }
}
